version: "3.9"
services:
  mysqldb:
    image: andreleaos/postgresdb:latest
    container_name: postgresdb
    networks:
      - compose-bridge
    ports:
      - 5436:5432
  gestaoapi:
    image: andreleaos/gestaodbapi:latest
    container_name: gestaodbapi
    networks:
      - compose-bridge
    ports:
      - 8082:80
    depends_on:
      - postgresdb	

networks:
  compose-bridge:
    driver: bridge
