version: "3.9"
services:
  mysqldb:
    image: andreleaos/sqlserverdb:latest
    container_name: sqlserverdb
    networks:
      - compose-bridge
    ports:
      - 1435:1433
  gestaoapi:
    image: andreleaos/gestaodbapi:latest
    container_name: gestaodbapi
    networks:
      - compose-bridge
    ports:
      - 8082:80
    depends_on:
      - sqlserverdb	

networks:
  compose-bridge:
    driver: bridge
