apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserverdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserverdb
  template:
    metadata:
      labels:
        app: sqlserverdb
    spec:
      containers:
        - name: sqlserverdb
          image: andreleaos/sqlserverdb:latest
          ports:
            - containerPort: 1433
---

apiVersion: v1
kind: Service
metadata:
  name: sqlserverdb-service
spec:
  selector:
    app: sqlserverdb
  ports:
    - protocol: TCP
      port: 1435
      targetPort: 1433
  type: NodePort  
